In [2]:
import pandas as pd

In [10]:
url = "D:/Basics_for_Machine_Learning_and_AI/Probability and Statistics/data/nhanes_2015_2016.csv"
da = pd.read_csv(url)

In [11]:
da.columns

Index(['SEQN', 'ALQ101', 'ALQ110', 'ALQ130', 'SMQ020', 'RIAGENDR', 'RIDAGEYR',
       'RIDRETH1', 'DMDCITZN', 'DMDEDUC2', 'DMDMARTL', 'DMDHHSIZ', 'WTINT2YR',
       'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'BPXSY1', 'BPXDI1', 'BPXSY2',
       'BPXDI2', 'BMXWT', 'BMXHT', 'BMXBMI', 'BMXLEG', 'BMXARML', 'BMXARMC',
       'BMXWAIST', 'HIQ210'],
      dtype='object')

In [13]:
da['BMXWT'].mean()     # we can get a mean

81.34267560889516

In [14]:
da['DMDEDUC2'].unique()     # Categorical Ordered

array([ 5.,  3.,  4.,  2., nan,  1.,  9.])

In [16]:
g = da['RIAGENDR']      # Categorical, Unordered
g

0       1
1       1
2       1
3       2
4       2
       ..
5730    2
5731    1
5732    2
5733    1
5734    2
Name: RIAGENDR, Length: 5735, dtype: int64

In [17]:
g.unique()

array([1, 2], dtype=int64)

# **One Hot Encoding**

In [19]:
import pandas as pd

B = ['bird', 'cat', 'dog', 'bird', 'bird']
d = {'categorical': B}

df = pd.DataFrame(d)

In [20]:
df

  categorical
0        bird
1         cat
2         dog
3        bird
4        bird

In [22]:
# "dummies" is used to create columns corresponding to unique values
dfDummies = pd.get_dummies(df['categorical'], prefix='category')

In [23]:
dfDummies

   category_bird  category_cat  category_dog
0           True         False         False
1          False          True         False
2          False         False          True
3           True         False         False
4           True         False         False

In [29]:
dfDummies.values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False]])